const WA='917498169710';
const products=[
{id:1,name:'Airtight Kitchen Storage Container – 1.1L',category:'Storage',badge:'Bestseller',desc:'Smart, transparent storage for grains, snacks, spices and everyday kitchen essentials.',images:['assets/storage-container-1.jpeg','assets/storage-container-2.jpeg','assets/storage-container-3.jpeg','assets/storage-container-4.jpeg','assets/storage-container-5.jpeg'],features:['Airtight Seal','BPA Free Material','Stackable Design','Transparent Body'],size:'1.1 L',dims:'Approx. 16 cm height × 10.5 cm width',link:'https://fktr.in/A00I4I7'},
{id:2,name:'2-IN-1 Oil Sprayer & Pour Bottle',category:'Kitchen',badge:'Trending',desc:'Spray or pour from one smart kitchen bottle for controlled oil use and convenient cooking.',images:['assets/oil-sprayer-1.png','assets/oil-sprayer-2.jpeg','assets/oil-sprayer-3.jpeg','assets/oil-sprayer-4.jpeg','assets/oil-sprayer-5.jpeg','assets/oil-sprayer-6.jpeg'],features:['2-IN-1 Spray & Pour','Fine Mist Spray','Leak-Proof Design','Borosilicate Glass Bottle','Easy to Clean','Ergonomic Handle'],size:'2-IN-1',dims:'Approx. 7.21 in height × 4.08 in width',link:'https://fktr.in/BiMH68X'},
{id:3,name:'Premium Stainless Steel Bottle',category:'Lifestyle',badge:'Premium Pick',desc:'A stylish 1-litre stainless steel bottle for desk, gym, office and travel.',images:['assets/bottle-1.jpeg','assets/bottle-2.jpeg','assets/bottle-3.jpeg','assets/bottle-4.jpeg','assets/bottle-5.jpeg','assets/bottle-6.jpeg'],features:['BPA Free','Leak Proof','1 Litre Capacity','Easy to Carry','Non-Toxic','Multi-Purpose'],size:'1 Litre',dims:'27 cm height × 8 cm width',link:'https://fktr.in/l2lUkZq'},
{id:4,name:'Stainless Steel Food Storage Containers – 5 Piece Set',category:'Storage',badge:'Premium Pick',desc:'A practical stainless steel storage set with five stackable containers and easy-to-clean lids.',images:['assets/storage-set-1.jpeg','assets/storage-set-2.jpeg','assets/storage-set-3.jpeg','assets/storage-set-4.jpeg','assets/storage-set-5.jpeg'],features:['5-Piece Set','Stainless Steel','Dishwasher Safe','Fridge & Freezer Safe','Rust Free','Easy to Clean','BPA Free','Made in India'],size:'5 Piece Set',dims:'160 ml • 300 ml • 500 ml • 600 ml • 1000 ml',link:'https://fktr.in/tVzv2ts'}];
let filter='All',cart=[];
const $=id=>document.getElementById(id);
function render(){let q=($('searchInput').value||'').trim().toLowerCase();let c=$('searchCategory').value;let list=products.filter(p=>(filter==='All'||p.category===filter)&&(c==='All'||p.category===c)&&(!q||p.name.toLowerCase().includes(q)||p.desc.toLowerCase().includes(q)));$('productGrid').innerHTML=list.map(p=>`<article class="product"><div class="pimg"><span class="badge">${p.badge}</span><img src="${p.images[0]}" alt="${p.name}"></div><div class="pbody"><div class="cat">${p.category}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="actions"><button class="view" onclick="openProduct(${p.id})">View Product</button><a class="wa" href="${waLink(p)}" target="_blank" rel="noopener">WhatsApp</a></div></div></article>`).join('')||'<p>No products found. Try another search.</p>';}
function waLink(p){return 'https://wa.me/'+WA+'?text='+encodeURIComponent('Hi ShambhoMART, I am interested in: '+p.name+'\nPlease share details/order information.')}
function openProduct(id){let p=products.find(x=>x.id===id);$('modalCat').textContent='SHAMBHOMART • '+p.category.toUpperCase();$('modalTitle').textContent=p.name;$('modalDesc').textContent=p.desc;$('modalSize').textContent=p.size+' • '+p.dims;$('modalFeatures').innerHTML=p.features.map(x=>'<li>✓ '+x+'</li>').join('');$('mainImage').src=p.images[0];$('mainImage').alt=p.name;$('thumbs').innerHTML=p.images.map((x,i)=>`<button class="thumb ${i?'':'selected'}" onclick="pickImage('${x}',this)"><img src="${x}" alt=""></button>`).join('');$('modalShop').href=p.link;$('modalWA').href=waLink(p);$('productModal').classList.add('show');}
function pickImage(src,b){$('mainImage').src=src;document.querySelectorAll('.thumb').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}
function updateCart(){ $('cartCount').textContent=cart.length;$('cartItems').innerHTML=cart.length?cart.map((id,i)=>{let p=products.find(x=>x.id===id);return `<div class="cartitem"><div><b>${p.name}</b><small>${p.category}</small></div><button onclick="removeCart(${i})">×</button></div>`}).join(''):'<p>Your selection is empty.</p>'; }
function removeCart(i){cart.splice(i,1);updateCart()}
function addCart(id){cart.push(id);updateCart()}
function order(){let names=cart.map(id=>products.find(p=>p.id===id).name);let text=names.length?'Hi ShambhoMART, I want to enquire/order:\n- '+names.join('\n- '):'Hi ShambhoMART, I want to know about your products.';window.open('https://wa.me/'+WA+'?text='+encodeURIComponent(text),'_blank')}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()}));
$('searchBtn').onclick=render;$('searchInput').oninput=render;$('searchCategory').onchange=render;$('cartBtn').onclick=()=>{$('drawer').classList.add('open');$('overlay').classList.add('show')};$('closeCart').onclick=()=>{$('drawer').classList.remove('open');$('overlay').classList.remove('show')};$('overlay').onclick=()=>{$('drawer').classList.remove('open');$('overlay').classList.remove('show')};$('whatsappOrder').onclick=order;$('clearCart').onclick=()=>{cart=[];updateCart()};$('closeProduct').onclick=()=>$('productModal').classList.remove('show');$('productModal').onclick=e=>{if(e.target.id==='productModal')$('productModal').classList.remove('show')};$('year').textContent=new Date().getFullYear();render();updateCart();
